/*
 * This file is generated by jOOQ.
 */
package de.acme.jooq.tables.records;


import de.acme.jooq.tables.Lied;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class LiedRecord extends UpdatableRecordImpl<LiedRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached LiedRecord
     */
    public LiedRecord() {
        super(Lied.LIED);
    }

    /**
     * Create a detached, initialised LiedRecord
     */
    public LiedRecord(String id, String titel) {
        super(Lied.LIED);

        setId(id);
        setTitel(titel);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>public.lied.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.lied.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>public.lied.titel</code>.
     */
    public String getTitel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lied.titel</code>.
     */
    public void setTitel(String value) {
        set(1, value);
    }
}
