/*
 * This file is generated by jOOQ.
 */
package de.acme.jooq.tables.records;


import de.acme.jooq.tables.Song;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class SongRecord extends UpdatableRecordImpl<SongRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached SongRecord
     */
    public SongRecord() {
        super(Song.SONG);
    }

    /**
     * Create a detached, initialised SongRecord
     */
    public SongRecord(String id, String titel) {
        super(Song.SONG);

        setId(id);
        setTitel(titel);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>public.song.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.song.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>public.song.titel</code>.
     */
    public String getTitel() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>public.song.titel</code>.
     */
    public void setTitel(String value) {
        set(1, value);
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }
}
