spring:
  application:
    name: acme
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/acmedb
    username: acme
    password: acme
  docker:
    compose:
      skip:
        in-tests: false
