spring:
  application:
    name: acme
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  datasource:
    hikari:
      maximum-pool-size: 80
    url: jdbc:postgresql://localhost:5432/acmedb
    username: acme
    password: acme
  docker:
    compose:
      skip:
        in-tests: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect