spring:
  application:
    name: acme
  #  liquibase:
  #    change-log: classpath:db/changelog/db.changelog-master.xml
  #    enabled: true
  datasource:
    hikari:
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/acmedb
    username: acme
    password: acme
  docker:
    compose:
      skip:
        in-tests: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
events:
  publisher:
    publish-events-to-application: true
    save-to-outbox: true
