/*
 * This file is generated by jOOQ.
 */
package de.acme.jooq;


import de.acme.jooq.tables.Benutzer;
import de.acme.jooq.tables.Lied;
import de.acme.jooq.tables.Playlist;
import de.acme.jooq.tables.PlaylistLied;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.benutzer</code>.
     */
    public final Benutzer BENUTZER = Benutzer.BENUTZER;

    /**
     * The table <code>public.lied</code>.
     */
    public final Lied LIED = Lied.LIED;

    /**
     * The table <code>public.playlist</code>.
     */
    public final Playlist PLAYLIST = Playlist.PLAYLIST;

    /**
     * The table <code>public.playlist_lied</code>.
     */
    public final PlaylistLied PLAYLIST_LIED = PlaylistLied.PLAYLIST_LIED;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
                Benutzer.BENUTZER,
                Lied.LIED,
                Playlist.PLAYLIST,
                PlaylistLied.PLAYLIST_LIED
        );
    }
}
