/*
 * This file is generated by jOOQ.
 */
package de.acme.jooq;


import de.acme.jooq.tables.Playlist;
import de.acme.jooq.tables.PlaylistSong;
import de.acme.jooq.tables.Song;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>public.playlist</code>.
     */
    public static final Playlist PLAYLIST = Playlist.PLAYLIST;

    /**
     * The table <code>public.playlist_song</code>.
     */
    public static final PlaylistSong PLAYLIST_SONG = PlaylistSong.PLAYLIST_SONG;

    /**
     * The table <code>public.song</code>.
     */
    public static final Song SONG = Song.SONG;
}
