/*
 * This file is generated by jOOQ.
 */
package de.acme.jooq.tables;


import de.acme.jooq.Keys;
import de.acme.jooq.Public;
import de.acme.jooq.tables.Lied.LiedPath;
import de.acme.jooq.tables.Playlist.PlaylistPath;
import de.acme.jooq.tables.records.PlaylistLiedRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PlaylistLied extends TableImpl<PlaylistLiedRecord> {

    /**
     * The reference instance of <code>public.playlist_lied</code>
     */
    public static final PlaylistLied PLAYLIST_LIED = new PlaylistLied();
    private static final long serialVersionUID = 1L;
    /**
     * The column <code>public.playlist_lied.lied_id</code>.
     */
    public final TableField<PlaylistLiedRecord, String> LIED_ID = createField(DSL.name("lied_id"), SQLDataType.VARCHAR.nullable(false), this, "");
    /**
     * The column <code>public.playlist_lied.playlist_id</code>.
     */
    public final TableField<PlaylistLiedRecord, String> PLAYLIST_ID = createField(DSL.name("playlist_id"), SQLDataType.VARCHAR.nullable(false), this, "");
    private transient LiedPath _lied;
    private transient PlaylistPath _playlist;

    private PlaylistLied(Name alias, Table<PlaylistLiedRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlaylistLied(Name alias, Table<PlaylistLiedRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.playlist_lied</code> table reference
     */
    public PlaylistLied(String alias) {
        this(DSL.name(alias), PLAYLIST_LIED);
    }

    /**
     * Create an aliased <code>public.playlist_lied</code> table reference
     */
    public PlaylistLied(Name alias) {
        this(alias, PLAYLIST_LIED);
    }

    /**
     * Create a <code>public.playlist_lied</code> table reference
     */
    public PlaylistLied() {
        this(DSL.name("playlist_lied"), null);
    }

    public <O extends Record> PlaylistLied(Table<O> path, ForeignKey<O, PlaylistLiedRecord> childPath, InverseForeignKey<O, PlaylistLiedRecord> parentPath) {
        super(path, childPath, parentPath, PLAYLIST_LIED);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlaylistLiedRecord> getRecordType() {
        return PlaylistLiedRecord.class;
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PlaylistLiedRecord> getPrimaryKey() {
        return Keys.PK_PLAYLIST_LIED;
    }

    @Override
    public List<ForeignKey<PlaylistLiedRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PLAYLIST_LIED__FK_LIED_ID, Keys.PLAYLIST_LIED__FK_PLAYLIST_ID);
    }

    /**
     * Get the implicit join path to the <code>public.lied</code> table.
     */
    public LiedPath lied() {
        if (_lied == null)
            _lied = new LiedPath(this, Keys.PLAYLIST_LIED__FK_LIED_ID, null);

        return _lied;
    }

    /**
     * Get the implicit join path to the <code>public.playlist</code> table.
     */
    public PlaylistPath playlist() {
        if (_playlist == null)
            _playlist = new PlaylistPath(this, Keys.PLAYLIST_LIED__FK_PLAYLIST_ID, null);

        return _playlist;
    }

    @Override
    public PlaylistLied as(String alias) {
        return new PlaylistLied(DSL.name(alias), this);
    }

    @Override
    public PlaylistLied as(Name alias) {
        return new PlaylistLied(alias, this);
    }

    @Override
    public PlaylistLied as(Table<?> alias) {
        return new PlaylistLied(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaylistLied rename(String name) {
        return new PlaylistLied(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaylistLied rename(Name name) {
        return new PlaylistLied(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaylistLied rename(Table<?> name) {
        return new PlaylistLied(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistLied where(Condition condition) {
        return new PlaylistLied(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistLied where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistLied where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistLied where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistLied where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistLied where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistLied where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistLied where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistLied whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistLied whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PlaylistLiedPath extends PlaylistLied implements Path<PlaylistLiedRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> PlaylistLiedPath(Table<O> path, ForeignKey<O, PlaylistLiedRecord> childPath, InverseForeignKey<O, PlaylistLiedRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private PlaylistLiedPath(Name alias, Table<PlaylistLiedRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PlaylistLiedPath as(String alias) {
            return new PlaylistLiedPath(DSL.name(alias), this);
        }

        @Override
        public PlaylistLiedPath as(Name alias) {
            return new PlaylistLiedPath(alias, this);
        }

        @Override
        public PlaylistLiedPath as(Table<?> alias) {
            return new PlaylistLiedPath(alias.getQualifiedName(), this);
        }
    }
}
