/*
 * This file is generated by jOOQ.
 */
package de.acme.jooq.tables;


import de.acme.jooq.Keys;
import de.acme.jooq.Public;
import de.acme.jooq.tables.Playlist.PlaylistPath;
import de.acme.jooq.tables.PlaylistSong.PlaylistSongPath;
import de.acme.jooq.tables.records.SongRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Song extends TableImpl<SongRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.song</code>
     */
    public static final Song SONG = new Song();

    private transient PlaylistSongPath _playlistSong;

    /**
     * The column <code>public.song.id</code>.
     */
    public final TableField<SongRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.song.titel</code>.
     */
    public final TableField<SongRecord, String> TITEL = createField(DSL.name("titel"), SQLDataType.VARCHAR, this, "");

    private Song(Name alias, Table<SongRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Song(Name alias, Table<SongRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.song</code> table reference
     */
    public Song(String alias) {
        this(DSL.name(alias), SONG);
    }

    /**
     * Create an aliased <code>public.song</code> table reference
     */
    public Song(Name alias) {
        this(alias, SONG);
    }

    /**
     * Create a <code>public.song</code> table reference
     */
    public Song() {
        this(DSL.name("song"), null);
    }

    public <O extends Record> Song(Table<O> path, ForeignKey<O, SongRecord> childPath, InverseForeignKey<O, SongRecord> parentPath) {
        super(path, childPath, parentPath, SONG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SongPath extends Song implements Path<SongRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SongPath(Table<O> path, ForeignKey<O, SongRecord> childPath, InverseForeignKey<O, SongRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SongPath(Name alias, Table<SongRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SongPath as(String alias) {
            return new SongPath(DSL.name(alias), this);
        }

        @Override
        public SongPath as(Name alias) {
            return new SongPath(alias, this);
        }

        @Override
        public SongPath as(Table<?> alias) {
            return new SongPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<SongRecord> getPrimaryKey() {
        return Keys.SONG_PKEY;
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SongRecord> getRecordType() {
        return SongRecord.class;
    }

    /**
     * Get the implicit to-many join path to the
     * <code>public.playlist_song</code> table
     */
    public PlaylistSongPath playlistSong() {
        if (_playlistSong == null)
            _playlistSong = new PlaylistSongPath(this, null, Keys.PLAYLIST_SONG__FK_SONG_ID.getInverseKey());

        return _playlistSong;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.playlist</code> table
     */
    public PlaylistPath playlist() {
        return playlistSong().playlist();
    }

    @Override
    public Song as(String alias) {
        return new Song(DSL.name(alias), this);
    }

    @Override
    public Song as(Name alias) {
        return new Song(alias, this);
    }

    @Override
    public Song as(Table<?> alias) {
        return new Song(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Song rename(String name) {
        return new Song(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Song rename(Name name) {
        return new Song(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Song rename(Table<?> name) {
        return new Song(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Song where(Condition condition) {
        return new Song(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Song where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Song where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Song where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Song where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Song where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Song where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Song where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Song whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Song whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
